//Thor Patcher remote config file
[Main]
allow=true
Force_Start=false
policy_msg=Servidor em Manutencao.

; Link de onde o patcher vai baixar os arquivos .thor
file_url=https://raw.githubusercontent.com/allisonmdn/456121295142ptr/main/

[Patch]
ClientSum=
PatcherSum=
ClientPath=
PatcherPath=

; Nome da lista que o robô do GitHub gera sozinho
PatchList=plist.txt

[Stars]
clients=0

[Misc]
FragmentLimit=50
