name: Generate Thor Patcher Playlist

on:
  push:
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate plist.txt
      run: |
        echo "" > plist.txt
        count=1
        if [ -d "data" ]; then
          for file in $(ls data/*.thor 2>/dev/null | sort -V); do
            echo "$count $file" >> plist.txt
            count=$((count+1))
          done
        fi
        sed -i '/^[[:space:]]*$/d' plist.txt

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add plist.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Update plist.txt with new patches" && git push)
